blacklist:
- blend
- brand
- classic
- combination
- directions
- hoy
- i
- ice
- in
- just
- lo
- mix
- o
- oil
- only
- premium
- red
- rot
- rum
- s
- style
- t
- tea
- thin
- type
- version
descriptors:
- fresh
- frozen
- dried
- blanched
- steamed
- sweetened
- unsweetened
- canned
- instant
- chunky
- sliced
- grated
- crushed
- whole
- nonfat
- lowfat
- lean
- fatfree
- reduced
- condensed
- prepared
- thawed
- peeled
stopwords:
- with
- and
- from
- your
- for
- of
- only
- some
- a
- the
- to
- in
units:
- cup
- cups
- tbsp
- tablespoon
- tablespoons
- tsp
- teaspoon
- grams
- sticks
- ounces
- oz
- pound
- liters
- ml
- g
- lb
- can
- jar
- slice
- pack
- package
- stick
- serving
